jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1.6.0


    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1.6.0

      with:
        environment-url: 'https://org34c2cd83.crm8.dynamics.com/'
        user-name: 'hemanthbalam@azure232.onmicrosoft.com'
        password-secret: ${{ secrets.MYPASSWORD }}
        solution-name: custom
        solution-output-file: 'aSolution.zip'
        working-directory: 'out'

 
